# Hardware Parameters
CDMA_ENGINES_PER_CHIP = 10
MAX_CREDIT_CAPACITY = 2
DEFAULT_PCIE_X8_BANDWIDTH = 32  # Gbps
DEFAULT_PCIE_X4_BANDWIDTH = 16  # Gbps
DEFAULT_C2C_BANDWIDTH = 256     # Gbps

# Latency Parameters
PCIE_BASE_LATENCY = 100   # ns
C2C_BASE_LATENCY = 50     # ns
INTERNAL_PROCESSING_DELAY = 40  # ns

# Topology Limits
MAX_CASCADE_CHIPS = 4
MAX_SYSTEM_CHIPS = 128
