# CrossRing 3x3 拓扑配置 - 只覆盖与默认值不同的参数
topology:
  NUM_ROW: 3
  NUM_COL: 3

fifo:
  IQ_CH_DEPTH: 8
  EQ_CH_DEPTH: 8

tag:
  TL_ETAG_T2_UE_MAX: 8
  TL_ETAG_T1_UE_MAX: 12
  TR_ETAG_T2_UE_MAX: 12
  TU_ETAG_T2_UE_MAX: 8
  TU_ETAG_T1_UE_MAX: 12
  TD_ETAG_T2_UE_MAX: 12

tracker:
  SN_L2M_R_TRACKER_OSTD: 64
  SN_L2M_W_TRACKER_OSTD: 64

latency:
  DDR_W_LATENCY: 16