# CrossRing 3x3 拓扑配置
topology:
  num_row: 3
  num_col: 3

basic:
  network_frequency: 2

tracker:
  rn_r_tracker_ostd: 128
  rn_w_tracker_ostd: 32
  sn_ddr_r_tracker_ostd: 32
  sn_ddr_w_tracker_ostd: 16
  sn_l2m_r_tracker_ostd: 64
  sn_l2m_w_tracker_ostd: 64
  sn_tracker_release_latency: 40

latency:
  ddr_r_latency: 155
  ddr_w_latency: 16
  l2m_r_latency: 12
  l2m_w_latency: 16

fifo:
  iq_ch_depth: 8
  eq_ch_depth: 8
  iq_out_fifo_depth: 8
  rb_out_fifo_depth: 8
  rb_in_fifo_depth: 16
  eq_in_fifo_depth: 16

tag:
  tl_etag_t2_ue_max: 8
  tl_etag_t1_ue_max: 12
  tr_etag_t2_ue_max: 12
  tu_etag_t2_ue_max: 8
  tu_etag_t1_ue_max: 12
  td_etag_t2_ue_max: 12
  etag_bothside_upgrade: 0