# CrossRing 5x4 拓扑配置 - 只覆盖与默认值不同的参数
topology:
  NUM_ROW: 5
  NUM_COL: 4

fifo:
  IQ_CH_DEPTH: 4
  EQ_CH_DEPTH: 4

tracker:
  RN_R_TRACKER_OSTD: 64
  RN_W_TRACKER_OSTD: 64
  SN_DDR_R_TRACKER_OSTD: 64
  SN_DDR_W_TRACKER_OSTD: 64
  SN_L2M_R_TRACKER_OSTD: 64
  SN_L2M_W_TRACKER_OSTD: 64

latency:
  DDR_R_LATENCY: 40

tag:
  ITAG_TRIGGER_TH_H: 80
  ITAG_TRIGGER_TH_V: 80
  ITAG_MAX_NUM_H: 1
  ITAG_MAX_NUM_V: 1