# CrossRing 默认配置 - 所有参数的默认值
# 具体拓扑配置文件会继承这些默认值，只需覆盖不同的参数

topology:
  NUM_ROW: 4
  NUM_COL: 2

basic:
  BURST: 4
  NETWORK_FREQUENCY: 2
  SLICE_PER_LINK: 8
  FLIT_SIZE: 128
  ROUTING_STRATEGY: "XY"
  SELF_LINK_SLICES: 2

ip:
  GDMA_COUNT: 16
  SDMA_COUNT: 16
  CDMA_COUNT: 16
  DDR_COUNT: 16
  L2M_COUNT: 16
  GDMA_BW_LIMIT: 128.0
  SDMA_BW_LIMIT: 128.0
  CDMA_BW_LIMIT: 32.0
  DDR_BW_LIMIT: 128.0
  L2M_BW_LIMIT: 128.0
  GDMA_RW_GAP: 1000000000
  SDMA_RW_GAP: 1000000000
  IP_L2H_FIFO_DEPTH: 3
  IP_H2L_H_FIFO_DEPTH: 2
  IP_H2L_L_FIFO_DEPTH: 2

fifo:
  RB_IN_FIFO_DEPTH: 16
  RB_OUT_FIFO_DEPTH: 8
  IQ_OUT_FIFO_DEPTH: 8
  EQ_IN_FIFO_DEPTH: 16
  IQ_CH_DEPTH: 10
  EQ_CH_DEPTH: 10

tag:
  ITAG_TRIGGER_TH_H: 80
  ITAG_TRIGGER_TH_V: 80
  ITAG_MAX_NUM_H: 1
  ITAG_MAX_NUM_V: 1
  ETAG_BOTHSIDE_UPGRADE: 0
  TL_ETAG_T1_UE_MAX: 15
  TL_ETAG_T2_UE_MAX: 8
  TR_ETAG_T2_UE_MAX: 12
  TU_ETAG_T1_UE_MAX: 15
  TU_ETAG_T2_UE_MAX: 8
  TD_ETAG_T2_UE_MAX: 12

tracker:
  RN_R_TRACKER_OSTD: 128
  RN_W_TRACKER_OSTD: 32
  SN_DDR_R_TRACKER_OSTD: 32
  SN_DDR_W_TRACKER_OSTD: 16
  SN_L2M_R_TRACKER_OSTD: 96
  SN_L2M_W_TRACKER_OSTD: 48
  SN_TRACKER_RELEASE_LATENCY: 40

latency:
  DDR_R_LATENCY: 155
  DDR_R_LATENCY_VAR: 0
  DDR_W_LATENCY: 0
  DDR_W_LATENCY_VAR: 0
  L2M_R_LATENCY: 12
  L2M_R_LATENCY_VAR: 0
  L2M_W_LATENCY: 16
  L2M_W_LATENCY_VAR: 0